### ISSUE TITLE
Is this still needed?

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric-language-groovy#4]
Looking at the current language adapter, I say this can go dormant as the language adapter is useless now. It just calls the default language adapter without doing anything. Mods should just use the default adapter and ship groovy.

**Comment by i509VCB** [comment]
Unless everyone shadows groovy, it's gonna be version hell without something common to bundle the standard library for groovy

**Comment by TheSledgeHammer** [comment]
> Unless everyone shadows groovy, it's gonna be version hell without something common to bundle the standard library for groovy

I agree. It would also still require something very similar to what the language adapter already does, just repeated across each mod.

Also unless something has changed with how Java handles Groovy Objects. Removing the language adapter would also result in Java throwing null pointer exceptions for Groovy Objects, with any mod that uses Groovy.
Very similar to how Scala works.

**Comment by liach** [comment]
as i see, this adapter now does not handle groovy objects.

**Comment by Juuxel** [comment]
Yeah. The adapter is basically a useless fallback to `DefaultLanguageAdapter` (which itself is not even an API class) with just an extra if check that doesn't lead to any actual behaviour:

https://github.com/FabricMC/fabric-language-groovy/blob/1729601f824d9b942c40e7a487ba82ea5252a814/src/main/groovy/net/fabricmc/language/groovy/GroovyLanguageAdapter.groovy#L14-L21

(not to mention that `Class.forName(aClass.getName())` just returns the same class object)

IMO it should just be removed and this language adapter should just shadow Groovy. Also, it includes `groovy-all`, which depends on many completely unnecessary Groovy modules like `groovy-swing` or `groovy-servlet` - it should just include the base jar.

**Comment by modmuss50** [comment]
I believe one of the reasons we kept the adapter was to allow future expansion/fixes without breaking mods.

As for replacing groovy-all with something more refined that does need doing. right now the jar file is massive.

**Comment by Juuxel** [comment]
> I believe one of the reasons we kept the adapter was to allow future expansion/fixes without breaking mods.

Removing the if check would still be good as it should always be false (`groovyClass.equals(aClass) -> groovyClass != null`), so it doesn't do anything.

> As for replacing groovy-all with something more refined that does need doing. right now the jar file is massive.

Looking through the [Groovy modules](https://search.maven.org/search?q=g:org.codehaus.groovy) on Maven Central, I don't think FLG necessarily even needs any other modules than the base? If something like `groovy-nio` is needed, it can be added later.

**Comment by liach** [comment]
i looked at groovy's doc on its singleton anno when someone mentioned it. maybe we can try support obtaining instance through getInstance, its default generated static method (unfortunately, other method names exist and the annotation is source retention)

**Comment by TheSledgeHammer** [comment]
Your right it doesn't do anything, except provide access to Groovy.
The issue i see that you are not solving. Is that when you compile groovy code, The compiler automatically implements GroovyObject. 

So you still need some form of groovy class, otherwise Java cannot handle the GroovyObject Implementation.

I provided what the class file looks like compiled below.

```
package net.fabricmc.language.groovy;

import groovy.lang.GroovyObject;
import groovy.lang.MetaClass;
import groovy.transform.Generated;
import groovy.transform.Internal;
import java.beans.Transient;
import java.lang.ref.SoftReference;
import net.fabricmc.loader.api.LanguageAdapter;
import net.fabricmc.loader.api.LanguageAdapterException;
import net.fabricmc.loader.api.ModContainer;
import net.fabricmc.loader.util.DefaultLanguageAdapter;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.codehaus.groovy.reflection.ClassInfo;
import org.codehaus.groovy.runtime.GStringImpl;
import org.codehaus.groovy.runtime.ScriptBytecodeAdapter;
import org.codehaus.groovy.runtime.callsite.CallSite;
import org.codehaus.groovy.runtime.callsite.CallSiteArray;
import org.codehaus.groovy.runtime.typehandling.ShortTypeHandling;

public class GroovyLanguageAdapter implements LanguageAdapter, GroovyObject {
  private Logger LOGGER;
  
  @Generated
  public GroovyLanguageAdapter() {
    Object object = arrayOfCallSite[0].call(LogManager.class, "GroovyLanguageAdapter");
    this.LOGGER = (Logger)ScriptBytecodeAdapter.castToType(object, Logger.class);
    MetaClass metaClass = $getStaticMetaClass();
  }
  
  public <T> T create(ModContainer modContainer, String s, Class aClass) throws LanguageAdapterException {
    CallSite[] arrayOfCallSite = $getCallSiteArray();
    Class<?> groovyClass = Class.forName(ShortTypeHandling.castToString(arrayOfCallSite[1].call(aClass)));
    if (ScriptBytecodeAdapter.compareEqual(groovyClass, null))
      arrayOfCallSite[2].call(this.LOGGER, new GStringImpl(new Object[] { arrayOfCallSite[3].callGetProperty(aClass) }, new String[] { "Unable to find Groovy object instance for ", ", constructing new instance" })); 
    return (T)arrayOfCallSite[4].call(arrayOfCallSite[5].callGetProperty(DefaultLanguageAdapter.class), modContainer, s, aClass);
  }
  
  @Generated
  @Internal
  @Transient
  public MetaClass getMetaClass() {
    if (this.metaClass != null)
      return this.metaClass; 
    this.metaClass = $getStaticMetaClass();
    return this.metaClass;
  }
  
  @Generated
  @Internal
  public void setMetaClass(MetaClass paramMetaClass) {
    this.metaClass = paramMetaClass;
  }
}
```

**Comment by liach** [comment]
> Java cannot handle the GroovyObject Implementation

Really? I fail to see how your code magically brings GroovyObject compatibility to the default language adapter.

**Comment by Juuxel** [comment]
`GroovyObject` is just an interface, and I don't see why it needs any special support from the language adapter either? As you can see even from the current language adapter implementation, it shouldn't need anything special (including no-op if checks).

**Comment by TheSledgeHammer** [comment]
Ok. I'm not opposed to changes and improvements. 

I just wanted to make sure you understood, where I was coming from.

So if you have ideas and can do it better or improve it. I'm all for it.

**Comment by liach** [comment]
So is removing these lines fine?
https://github.com/FabricMC/fabric-language-groovy/blob/1729601f824d9b942c40e7a487ba82ea5252a814/src/main/groovy/net/fabricmc/language/groovy/GroovyLanguageAdapter.groovy#L16-L19

Like the `groovyClass` is not used when calling the default language adapter; it uses `aClass` instead.

**Comment by TheSledgeHammer** [comment]
Lmao now I see what you're talking about. That is a mistake on my part. It was meant to return groovyClass inside the default adapter not aclass.

Yes. It's fine.

**Comment by liach** [comment]
Hmm, does groovy have a special logic for Class.forName that allows retrieving singleton? If yes implementing that here would be helpful as the default adapter cannot get an instance from a method (it only converts the method to a proxy)

**Comment by shedaniel** [comment]
Please at least make this not shadow the groovy packages so it doesn't break with my superior way of JIJing the groovy libs myself because I don't need half of the things in this language adapter.

**Comment by liach** [comment]
So you mean you actually don't use the language adapter because it ships too much groovy? groovy!

**Comment by shedaniel** [comment]
Well you see, this language adapter is exactly the same as the default one, and this thing shadows stuff like groovy-swing and groovy-sql, really does make you wonder why the jar is 18MB right? There is no apparent benefits of using this project.

**Comment by modmuss50** [comment]
Saying that this project has no benefit is wrong imo. The whole point of it is to include the groovy libs. If you want to use the adpater part of it you can choose if you want to or not. The main reason I suggested to add it when it was written was incase we wanted to expand it in the future.

As for the extra deps no one is going to need those can easily be excluded.

**Comment by liach** [comment]
so should this adapter exclude groovy sql/swing then?

**Comment by Juuxel** [comment]
It should just use the `org.codehaus.groovy:groovy` artifact instead of groovy-all. Most things in groovy-all are not needed in MC modding so we can go with the base language API for now IMO. (Any other useful modules can be included in addition to the base one, like FLK does with coroutines etc)

**Comment by TheSledgeHammer** [comment]
> 
> 
>  There is no apparent benefits of using this project.

I think that is an unfair comment lol.
FYI it included the groovy-all because of JAX, back in Minecraft 1.12.2. Groovy-all is overkill.
 It has only ever had 1 person actively updating it, periodically.

> 
> 
> Hmm, does groovy have a special logic for Class.forName that allows retrieving singleton? If yes implementing that here would be helpful as the default adapter cannot get an instance from a method (it only converts the method to a proxy)

There is Class.getAnnontation and various methods for annontations, but nothing specific to singletons
